parameters:
    env(LUIGIS_BOX_API_URL): 'https://rtp.luigisBox.ai/'
    env(LUIGIS_BOX_ACCOUNT_ID): ''
    env(LUIGIS_BOX_IS_PRODUCTION_MODE): 'false'
    env(LUIGIS_BOX_RECOMMENDATION_ALGORITHM_ID): ''
    luigisBox.recommendation.algorithm_id: '%env(LUIGIS_BOX_RECOMMENDATION_ALGORITHM_ID)%'
    env(LUIGIS_BOX_RECOMMENDATION_OFFER_ID): ''
    luigisBox.recommendation.offer_id: '%env(LUIGIS_BOX_RECOMMENDATION_OFFER_ID)%'
    env(LUIGIS_BOX_RECOMMENDATION_LOCATION_ID): ''
    luigisBox.recommendation.location_id: '%env(LUIGIS_BOX_RECOMMENDATION_LOCATION_ID)%'
    env(LUIGIS_BOX_SEARCH_ALGORITHM_ID): ''
    luigisBox.search.algorithm_id: '%env(LUIGIS_BOX_SEARCH_ALGORITHM_ID)%'
    env(LUIGIS_BOX_SEARCH_OFFER_ID): ''
    luigisBox.search.offer_id: '%env(LUIGIS_BOX_SEARCH_OFFER_ID)%'
    env(LUIGIS_BOX_SEARCH_LOCATION_ID): ''
    luigisBox.search.location_id: '%env(LUIGIS_BOX_SEARCH_LOCATION_ID)%'
    env(LUIGIS_BOX_ENABLED_DOMAIN_IDS): ''
    luigisBox.enabled_domain_ids: '%env(LUIGIS_BOX_ENABLED_DOMAIN_IDS)%'
